services:
  app:
    build:
      context: .
    image: raferreira96/node
    container_name: app
    restart: always
    tty: true
    entrypoint: dockerize -wait tcp://db:3306 -timeout 10s docker-entrypoint.sh
    command: node index.js
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - node
    depends_on:
      - db

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0 --explicit_defaults_for_timestamp=true
    restart: always
    tty: true
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: node
      MYSQL_USER: node
      MYSQL_PASSWORD: node
    networks:
      - node

networks:
  node:
      driver: bridge